config/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings

from tools.various.decorators import required, login_required_flat

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('exampleapp.urls', app_name='exampleapp', namespace='exampleapp')),
]

urlpatterns += required(
    login_required_flat,
    patterns('',
             (r'^control/api/', include('tools.files.urls')),
             (r'^control/', include('tools.various.urls')),
             (r'^control/', include('control.urls', app_name='control', namespace='control')), )
)

handler404 = 'exampleapp.views.custom_404'
handler500 = 'exampleapp.views.custom_500'


if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                                {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}), )

control/urls.py
from django.conf.urls import patterns, url

from config.settings import LANGUAGES_TUPLE
from control.api import ContactAjaxView, DirectionsAjaxView, BannerAjaxView, OfficeAjaxView


langs = '|'.join(LANGUAGES_TUPLE)

urlpatterns = patterns('control',
                        url(r'^$', 'views.index', name='control-main'),
                        url(r'^directions/$', 'views.directions', name='directions'),
                        url(r'^contacts/(?P<lang>(' + langs + '))/$', 'views.contacts', name='contacts'), )

# API
urlpatterns += patterns('control',
                        url(r'^api/banners/$', BannerAjaxView.as_view()),
                        url(r'^api/directions/$', DirectionsAjaxView.as_view(), name='api-directions'),
                        url(r'^api/offices/$', OfficeAjaxView.as_view(), name='api-offices'),
                        url(r'^api/contacts/$', ContactAjaxView.as_view(), name='api-contacts'), )

control/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.utils import translation
from exampleapp.models import Contact, Directions, Office, Depts


def index(request):
    return render(request, 'control/index.html', {})


def contacts(request, lang='ru'):
    translation.activate(lang)
    contacts = Office.export_control_all()
    # depts = Depts.objects.all()
    print contacts
    return render(request, 'control/contacts.html', {'contacts': contacts, 'lang': lang, })


def directions(request):
    directions = Directions.export_control_all()
    print directions
    return render(request, 'control/directions.html', {'directions': directions, })

templates/control/includes/topmenu.html
{% load control_tags %}

<div class="Topmenu">
    <div class="Topmenu-content Flex">
        <a class="Topmenu-logo" href="{% url 'control:control-main' %}"></a>

        {% spaceless %}
            <div class="Topmenu-list Flex">
                <a class="Topmenu-a {% active request '^/control/$' %}" href="{% url 'control:control-main' %}">
                    ГЛАВНАЯ
                </a>
                <a class="Topmenu-a {% active request '^/control/directions/$' %}" href="{% url 'control:control-main' %}">
                    НАПРАВЛЕНИЯ
                </a>
                <a class="Topmenu-a {% active request '^/control/contacts/$' %}" href="{% url 'control:contacts' lang='ru' %}">
                    КОНТАКТЫ
                </a>
                <a class="Topmenu-a {% active request '^/control/about/$' %}" href="{% url 'control:control-main' %}">
                    ХОЛДИНГ
                </a>
                <a class="Topmenu-a {% active request '^/control/news/$' %}" href="{% url 'control:control-main' %}">
                    НОВОСТИ
                </a>
            </div>
        {% endspaceless %}

        <a class="Topmenu-logout" href="{% url 'control-logout' %}">Выход</a>
    </div>
</div>